/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import communication.Communication;
import domain.Department;
import domain.Doctor;
import form.mode.FormMode;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import operations.Operation;
import transfer.ClientRequest;
import transfer.ServerResponse;

/**
 *
 * @author USER
 */
public class UserForm extends javax.swing.JDialog {

    /**
     * Creates new form UserForm
     */
     private Doctor doctor;
    private FormMode mode; // Dodato polje za mod

    public UserForm(java.awt.Frame parent, Doctor doctor, FormMode mode, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.doctor = doctor;
        this.mode = mode;
        fillCmb();
        setupForm(); // Inicijalizuje formu na osnovu moda
        
    }

    private void fillCmb() {
        try{
        
        cmbDepartment.removeAllItems();
        ClientRequest kz=new ClientRequest();
        
        kz.setOperacija(Operation.VRATI_ODELENJA);
        kz.setObjekatOperacije(new Department());
        
        Communication.getInstance().posaljiZahtev(kz);
        ServerResponse sod=Communication.getInstance().primiOdgovor();
        /*cmb moze i sa AbstractDO da se puni*/
        /*ABSTRACTDO PROBAJ AKO NE*/
        List<Department>lista=(List<Department>) sod.getOdgovor();
        cmbDepartment.setModel(new DefaultComboBoxModel(lista.toArray()));
        } catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Veza sa serverom je prekinuta!", "Greška", JOptionPane.ERROR_MESSAGE);
    System.exit(0); 
}
    }

    private void setupForm() {
        // Popunjavanje polja sa podacima doktora
        //ako velikim stavis onda ce uvek velikim u bazi ispis biti
        jTextFieldName.setText(doctor.getName());
        jTextFieldSurname.setText(doctor.getSurname());
        //equals!!!override
        cmbDepartment.setSelectedItem(doctor.getDepartment());

        // Podesavanje izgleda na osnovu moda
        if (mode == FormMode.FORM_VIEW) {
            customizeTextField(jTextFieldName, false, false, Color.lightGray, Color.black);
            customizeTextField(jTextFieldSurname, false, false, Color.lightGray, Color.black);
            cmbDepartment.setEnabled(false); // cmb ne mozes isto menjati
            jButtonUpdate.setVisible(false); //sakrij sacuvaj
            jButtonCancel.setVisible(false); // sakrij otkazi
        } else if (mode == FormMode.FORM_EDIT) {
            customizeTextField(jTextFieldName, true, true, Color.white, Color.black);
            customizeTextField(jTextFieldSurname, true, true, Color.white, Color.black);
            cmbDepartment.setEnabled(true); 
            jButtonUpdate.setVisible(true); 
            jButtonCancel.setVisible(true); 
        }
    }

private void customizeTextField(JTextField textField, boolean editable, boolean focusable, Color background, Color foreground) {
        textField.setEditable(editable);
        textField.setFocusable(focusable);
        textField.setBackground(background);
        textField.setForeground(foreground);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel1.setText("ULOGOVANI KORISNIK");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel2.setText("IME LEKARA");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel6.setText("PREZIME LEKARA");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel4.setText("ODELENJE");

        jButtonCancel.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCancel.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancel.setText("OTKAŽI");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(204, 204, 255));
        jButtonUpdate.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(204, 0, 0));
        jButtonUpdate.setText("IZMENI");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        jLabel3.setText("ULOGOVANI KORISNIK");

        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/5.png"))); // NOI18N
        jLabel7.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonUpdate))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
       
        try{
        doctor.setName(jTextFieldName.getText());
        doctor.setSurname(jTextFieldSurname.getText());
        Department selectedDepartment = (Department) cmbDepartment.getSelectedItem();

        doctor.setDepartment((Department) cmbDepartment.getSelectedItem());
         int i=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite izmeniti  podatke?", "IZMENA", JOptionPane.YES_NO_OPTION);
           if(i==JOptionPane.YES_OPTION){
               //kreiranej kz
               ClientRequest kz=new ClientRequest();
               kz.setObjekatOperacije(doctor);
               kz.setOperacija(Operation.IZMENI_KORISNIKA);
               //slanje 
               Communication.getInstance().posaljiZahtev(kz);
               //primanje odg
               ServerResponse odg=Communication.getInstance().primiOdgovor();

               JOptionPane.showMessageDialog(this, odg.getOdgovor(), "IZMENA", JOptionPane.INFORMATION_MESSAGE);     
             this.dispose();  
       }} 
        catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni podatke. " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE); 
        
            JOptionPane.showMessageDialog(this, "Veza sa serverom je prekinuta!", "Greška", JOptionPane.ERROR_MESSAGE);
       System.exit(0);}
        
        
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
