/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import dbbLoader.LoaderDiagnosis;
import dbbLoader.ExcelDataImporter;
import dbbLoader.LoaderProcedure;
import javax.swing.JOptionPane;
import dbbLoader.LoaderInterface;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 *
 * @author USER
 */
public class FormaUcitavanjeBaza extends javax.swing.JDialog {

    /**
     * Creates new form FormaUcitavanjeBaza
     */
    public FormaUcitavanjeBaza(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("UCITAJ DIJAGNOZE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("UCITAJ PROCEDURE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    try {
    LoaderInterface handler = new LoaderDiagnosis();  // interfejs inicijal na implem klasu diagnosisloader 
    ExcelDataImporter importer = new ExcelDataImporter(handler);  // importeru posaljes da inicijalizuje konst
    int signal=importer.loadDiagnoses("C:\\\\MKB102010Knjiga1errata2017.xls");
    
    if (signal==1) {//ako vec ucitan
        JOptionPane.showMessageDialog(this, "Dijagnoze su vec ucitane u bazu!", "VEC UCITANE", JOptionPane.ERROR_MESSAGE);
    } 
    else if(signal==-1){//ako npr ne pokrenes formu pa nastane greska
        JOptionPane.showMessageDialog(this, "Dijagnoze nisu učitane u bazu.Proverite da li ste pokrenuli server!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
    }
    else{
            JOptionPane.showMessageDialog(this, "Dijagnoze su uspešno učitane u bazu.", "USPESNO", JOptionPane.INFORMATION_MESSAGE);

    }
}  catch (Exception e) {
    // Generalni izuzetak za nepredviđene greške
    JOptionPane.showMessageDialog(this, "Došlo je do greške: " + e.getMessage(), "GREŠKA", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      try {
    LoaderInterface handler = new LoaderProcedure();  // Injekcija zavisnosti  
    ExcelDataImporter importer = new ExcelDataImporter(handler);  // saljemo tip koji je loaderprocedure
int signal=importer.loadProcedures("C:\\Procedure.xls");
    // Pokušaj učitavanja procedura iz Excel fajla
    if (signal==1) {//ako vec ucitan
        JOptionPane.showMessageDialog(this, "Procedure su već učitane u bazu!", "VEĆ UČITANE", JOptionPane.ERROR_MESSAGE);
    } 
    else if(signal==-1){//ako npr ne pokrenes formu pa nastane greska
        JOptionPane.showMessageDialog(this, "Procedure nisu učitane u bazu.Proverite da li ste pokrenuli server!", "USPESNO", JOptionPane.INFORMATION_MESSAGE);
    }
    else{
            JOptionPane.showMessageDialog(this, "Procedure su uspešno učitane u bazu.", "USPESNO", JOptionPane.INFORMATION_MESSAGE);

    }

}  catch (Exception e) {
    // Generalni izuzetak za nepredviđene greške
    JOptionPane.showMessageDialog(this, "Došlo je do greške: " + e.getMessage(), "GREŠKA", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
