/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controller.Controller;
import domain.Doctor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ModelTableUser;
import threads.ClientThread;
import threads.ServerThread;


public class ServerForm extends javax.swing.JFrame {

    
    ServerThread serverskaNit=null;
    private static ServerForm instance = null;
 

    ArrayList<Doctor>ado=new ArrayList<>();
    public static ServerForm getInstance() {
       
        if (instance == null) {
            instance = new ServerForm();
        }
        return instance;
    }
     public void updateStatus(String status, Color color) {
        jLabelStatus.setText(status);
        jLabelStatus.setForeground(color);
    }

    private ServerForm() {
       
     
        initComponents();
        //centriraj
        setLocationRelativeTo(null);
        //stavi formu za pocetak postavljenu
        setForm(ado);

         //forma controlleru koja se stavlja sada na vrednost ove forme
         //pa get ovu formu dobija u7 controlleru
        Controller.getInstance().setForma(this);
   
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jlbProgramName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jlbProgramName1 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jmbMain = new javax.swing.JMenuBar();
        jmAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonStart.setText("Pokreni");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonStop.setText("Zaustavi");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jlbProgramName.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jlbProgramName.setText("SERVER HITNE POMOĆI");

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsers);

        jlbProgramName1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jlbProgramName1.setText("Lista ulogovanih korisnika");

        jLabelStatus.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabelStatus.setText("SERVER NIJE POKRENUT!");

        jmAbout.setText("Konfiguracija");

        jmiAboutSoftware.setText("Konfiguracija");
        jmiAboutSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutSoftwareActionPerformed(evt);
            }
        });
        jmAbout.add(jmiAboutSoftware);

        jMenuItem1.setText("Učitavanje baze");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmAbout.add(jMenuItem1);

        jmbMain.add(jmAbout);

        setJMenuBar(jmbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jlbProgramName1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonStart)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jlbProgramName, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jlbProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jlbProgramName1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAboutSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutSoftwareActionPerformed
     
        DBConfigurationForm f=new DBConfigurationForm(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_jmiAboutSoftwareActionPerformed
//klik  na dugme pokreni
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
     if (serverskaNit == null || !serverskaNit.isAlive()) {
            try {
                serverskaNit = new ServerThread(this); // Prosledjujemo GUI formu
                serverskaNit.start(); // Pokrećemo nit
                jButtonStop.setVisible(true);
                jButtonStart.setVisible(false);
            } catch (Exception e) {
                serverskaNit = null;
                JOptionPane.showMessageDialog(this, "Greška pri pokretanju servera: " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Server je već pokrenut!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
            if(serverskaNit!=null){
             //treba odjaviti sve dr koji su prijavljeni 
             if(ado!=null){
            for(Doctor d:ado){
                try { 
                     d.setLogged(false);
            // unesi u bazu da je ulogovan
                    Controller.getInstance().postaviStatusLogovanja(d);
                    Controller.getInstance().postaviStatusLogovanja(d);
                } catch (Exception ex) {
                    Logger.getLogger(ServerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }}
            //treba odjaviti sve dr koji su prijavljeni 
            setForm(new ArrayList<>());
              serverskaNit.prekiniSveKlijente(); 
            serverskaNit.stopThread();
            serverskaNit = null; // Resetujemo referencu
                updateStatus("SERVER JE ZAUSTAVLJEN!", Color.RED);

            jButtonStop.setVisible(false);
            jButtonStart.setVisible(true);
        }

    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(serverskaNit==null){
        JOptionPane.showMessageDialog(this, "Pokrenite server!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        return;
        }
        FormaUcitavanjeBaza fdp=new FormaUcitavanjeBaza(this,true);
        fdp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
             
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {//MORA RUNNABLE !!
            public void run() {
                ServerForm.getInstance().setVisible(true);

            }
        });
    }
    
    void setForm(ArrayList<Doctor>ado){
      this.ado=ado;
      ModelTableUser mtu = new ModelTableUser(ado);
      jTableUsers.setModel(mtu);
      jButtonStop.setVisible(false);
       jLabelStatus.setForeground(Color.BLACK);

    }
    
//u klijentNit da doda u tabelu ulogovanog user-a
    //vraca model tabele korisnika sa server forme
    public ModelTableUser getTblUsers() {
        return (ModelTableUser) jTableUsers.getModel();
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JLabel jlbProgramName;
    private javax.swing.JLabel jlbProgramName1;
    private javax.swing.JMenu jmAbout;
    private javax.swing.JMenuBar jmbMain;
    private javax.swing.JMenuItem jmiAboutSoftware;
    // End of variables declaration//GEN-END:variables
}
